#!/usr/bin/perl
# "-i" mode loads the ruleset with iptables-restore instead of printing it.
# A fake iptables-restore on PATH records what it would have loaded.
use strict;
use warnings;
use lib 't/lib';
use GenfwTest;
use Test::More;

my %ifcfg = (
    eth0 => "DEVICE=eth0\nBOOTPROTO=dhcp\n",
    eth1 => "DEVICE=eth1\nIPADDR=192.168.1.1\nNETMASK=255.255.255.0\n",
);
my $rules = "int eth1 nat\nout eth0\nappend INPUT -m comment --comment word -j ACCEPT\n";

# Interface iteration order comes from hash order, which differs between
# perl processes unless the seed is pinned. Pin it so two runs can be
# compared line by line.
my %stable = (PERL_HASH_SEED => 0, PERL_PERTURB_KEYS => 0);

# Script mode output, for comparison.
my $script = run_genfw(make_fixture(rules => $rules, ifcfg => \%ifcfg), env => { %stable });

# -i feeds the ruleset to iptables-restore on stdin, and it is exactly the
# text that script mode prints.
{
    my ($bindir, $log) = fake_iptables_restore();
    my $res = run_genfw(
        make_fixture(rules => $rules, ifcfg => \%ifcfg),
        opts => ['-i', '-d'],
        env  => { %stable, PATH => "$bindir:$ENV{PATH}" },
    );
    is($res->{status}, 0, '-i exits 0');
    is($res->{stdout}, '', '-i prints nothing to stdout');
    ok(length(read_file($log)), 'fake iptables-restore received input');
    is(read_file($log), $script->{stdout}, '-i sends iptables-restore exactly what script mode prints');
}

# An iptables-restore failure means the firewall was not (fully) loaded, so
# it is fatal rather than a warning.
{
    my ($bindir, $log) = fake_iptables_restore();
    my $res = run_genfw(
        make_fixture(rules => $rules, ifcfg => \%ifcfg),
        opts => ['-i', '-d'],
        env  => { %stable, PATH => "$bindir:$ENV{PATH}", GENFW_FAKE_EXIT => 3 },
    );
    isnt($res->{status}, 0, 'iptables-restore failure makes genfw exit non-zero');
    ok((grep { /'iptables-restore' failed with exit value 3/ } @{$res->{warnings}}), 'failure message names the loader and its exit value');
    ok(length(read_file($log)), 'the ruleset was still sent in full before the failure was reported');
}

# The header identifies the format and how to load it.
{
    like($script->{stdout}, qr/\A# Generated by genfw \d/, 'header names genfw and the version');
    like($script->{stdout}, qr/^# Load with: iptables-restore/m, 'header says how to load the file');
    like($script->{stdout}, qr/^\*filter$/m, 'has a filter table block');
    like($script->{stdout}, qr/^COMMIT$/m, 'has a COMMIT line');
    is(($script->{stdout} =~ tr/\n//), scalar(split /\n/, $script->{stdout}), 'every line is newline-terminated');
}

# Script mode without -d reads from /etc/sysconfig; we can't test that
# directly, but -d alone must not require -i.
{
    my $res = run_genfw(make_fixture(rules => $rules, ifcfg => \%ifcfg), opts => ['-d']);
    like($res->{stdout}, qr/^\*filter$/m, 'script mode emits an iptables-restore file');
    like($res->{stdout}, qr/^# /m, 'script mode includes comments');
}

# DEBUG in the environment behaves like -d.
{
    my $res = run_genfw(make_fixture(rules => $rules, ifcfg => \%ifcfg), opts => [], env => { DEBUG => 1 });
    is($res->{status}, 0, 'DEBUG=1 reads config from the current directory');
    like($res->{stderr}, qr/^d: /m, 'DEBUG=1 emits debug tracing');
    like($res->{stderr}, qr/\$VAR1 = \{/, 'DEBUG=1 dumps the interface table');
}

done_testing;
