#!/usr/bin/perl
# The nft output format: the iptables ruleset translated by
# iptables-restore-translate, wrapped so that nft -f replaces genfw's tables
# atomically. Needs the translator; the real-load checks also need nft and
# an unprivileged network namespace.
use strict;
use warnings;
use lib 't/lib';
use GenfwTest;
use Test::More;
use Cwd qw(abs_path);
use File::Spec;
use File::Temp qw(tempfile);

plan skip_all => 'iptables-restore-translate not found in PATH (iptables-nft)'
    unless grep { -x "$_/iptables-restore-translate" } split /:/, $ENV{PATH};

my ($vol, $dir) = File::Spec->splitpath(abs_path(__FILE__));
my $sample = File::Spec->catdir($dir, 'sample');
my %stable = (PERL_HASH_SEED => 0, PERL_PERTURB_KEYS => 0);
my %ifcfg = (
    eth0 => "DEVICE=eth0\nBOOTPROTO=dhcp\n",
    eth1 => "DEVICE=eth1\nIPADDR=192.168.1.1\nNETMASK=255.255.255.0\n",
);

# --- Shape of the nft output for the sample configuration.
my $ipt = run_genfw($sample, env => { %stable });
my $nft = run_genfw($sample, opts => ['-d', '-o', 'nft'], env => { %stable });
{
    is($nft->{status}, 0, '-o nft generates');
    is_deeply($nft->{warnings}, [], 'no warnings') or diag(join "\n", @{$nft->{warnings}});
    like($nft->{stdout}, qr{\A#!/usr/sbin/nft -f\n# Generated by genfw \d}, 'starts with an nft shebang and the genfw header');
    unlike($nft->{stdout}, qr/Translated by|Completed on/, 'translator timestamps are stripped');

    my @lines = split /\n/, $nft->{stdout};
    for my $t (qw(filter nat mangle raw)) {
        my @idiom = grep { /^(add|delete) table ip $t$/ } @lines;
        is_deeply(\@idiom, ["add table ip $t", "delete table ip $t", "add table ip $t"], "table $t is added, deleted, and re-added so the load replaces it atomically");
    }
    is(scalar(grep { /^add rule / } @lines), scalar(@{ $ipt->{rules} }), 'every iptables rule has an nft counterpart');

    # Built-in chains in every table are declared with their hooks; nft
    # needs them where iptables-restore assumed them.
    like($nft->{stdout}, qr/^add chain ip filter INPUT \{ type filter hook input priority 0; policy drop; \}$/m, 'INPUT declared with hook and DROP policy');
    like($nft->{stdout}, qr/^add chain ip filter OUTPUT \{ type filter hook output priority 0; policy accept; \}$/m, 'OUTPUT declared with ACCEPT policy');
    like($nft->{stdout}, qr/^add chain ip nat POSTROUTING \{ type nat hook postrouting priority 100; policy accept; \}$/m, 'nat POSTROUTING declared (iptables-restore never needed this)');
    like($nft->{stdout}, qr/^add chain ip mangle PREROUTING \{ type filter hook prerouting priority -150; policy accept; \}$/m, 'mangle PREROUTING declared');
    like($nft->{stdout}, qr/^add chain ip filter inside-world$/m, 'user and pair chains declared');
    like($nft->{stdout}, qr/^add rule ip nat POSTROUTING oifname "eth0" ip saddr 192\.168\.1\.0\/24 counter masquerade$/m, 'a NAT rule translated');
    like($nft->{stdout}, qr/log prefix "world -> inside: "/, 'log prefixes with spaces survive translation');

    my $again = run_genfw($sample, opts => ['-d', '-o', 'nft'], env => { %stable });
    is($again->{stdout}, $nft->{stdout}, 'output is deterministic');
}

# --- Selecting the format.
{
    my $res = run_genfw(make_fixture(rules => "format nft\nint eth1\nout eth0\n", ifcfg => \%ifcfg));
    like($res->{stdout}, qr{\A#!/usr/sbin/nft -f}, 'the format directive selects nft');

    $res = run_genfw(make_fixture(rules => "format nft\nint eth1\nout eth0\n", ifcfg => \%ifcfg), opts => ['-d', '-o', 'iptables-restore']);
    like($res->{stdout}, qr{\A#!/usr/sbin/iptables-restore}, '-o overrides the directive');

    $res = run_genfw(make_fixture(rules => "format ipfw\nint eth1\nout eth0\n", ifcfg => \%ifcfg));
    ok((grep { /Unknown output format 'ipfw' \(line 1\); expected iptables-restore or nft/ } @{$res->{warnings}}), 'unknown format directive warns');
    like($res->{stdout}, qr{\A#!/usr/sbin/iptables-restore}, 'and the default is used');

    $res = run_genfw(make_fixture(rules => "int eth1\nout eth0\n", ifcfg => \%ifcfg), opts => ['-d', '-o', 'ipfw']);
    isnt($res->{status}, 0, 'unknown -o format is fatal');
    like($res->{stderr}, qr/Unknown output format 'ipfw'; expected one of: iptables-restore, nft/, 'and lists the choices');
}

# --- A rule the translator cannot handle is fatal, not silently dropped.
{
    my $res = run_genfw(make_fixture(
        rules => "format nft\nint eth1\nout eth0\nappend INPUT -m string --string evil --algo bm -j DROP\n",
        ifcfg => \%ifcfg,
    ));
    isnt($res->{status}, 0, 'an untranslatable rule makes genfw fail');
    like($res->{stderr}, qr/These rules have no nft translation/, 'the error explains why');
    like($res->{stderr}, qr/-A INPUT -m string --string evil/, 'and names the rule');
    is($res->{stdout}, '', 'nothing is emitted');
}

# --- -i with the nft backend: check with nft -c, then load with nft -f.
{
    my ($bindir, $log) = fake_command('nft', '-c -f -');
    my $res = run_genfw($sample, opts => ['-d', '-o', 'nft', '-i'], env => { %stable, PATH => "$bindir:$ENV{PATH}" });
    is($res->{status}, 0, '-i -o nft exits 0');
    is($res->{stdout}, '', 'prints nothing');
    is(read_file("$log.args"), "-c -f -\n-f -\n", 'nft is run with -c -f - first, then -f -');
    is(read_file($log), $nft->{stdout} x 2, 'both invocations receive exactly the nft text');

    ($bindir, $log) = fake_command('nft', '-c -f -');
    $res = run_genfw($sample, opts => ['-d', '-o', 'nft', '-i'], env => { %stable, PATH => "$bindir:$ENV{PATH}", GENFW_FAKE_EXIT => 3 });
    isnt($res->{status}, 0, 'nft -c failure is fatal');
    ok((grep { /'nft -c -f -' failed with exit value 3/ } @{$res->{warnings}}), 'and names the check step');
    is(read_file("$log.args"), "-c -f -\n", 'no load is attempted after a failed check');
}

# --- Real load: nft -f in a private network namespace. iptables-nft cannot
#     read back rules it did not create itself (it reports the tables as
#     "incompatible, use nft tool"), so the check is done with nft.
SKIP: {
    skip 'nft not found in PATH', 6 unless grep { -x "$_/nft" } split /:/, $ENV{PATH};
    skip 'unshare not found in PATH', 6 unless grep { -x "$_/unshare" } split /:/, $ENV{PATH};
    my $probe = qx(unshare -rn sh -c 'printf "add table ip t\\n" | nft -f - && nft list tables' 2>&1);
    skip 'nft does not work in an unprivileged namespace here', 6 unless $? == 0 && $probe =~ /table ip t/;

    my ($fh, $file) = tempfile('genfw-nft-XXXXXX', TMPDIR => 1, UNLINK => 1);
    print $fh $nft->{stdout};
    close $fh;

    # Load twice: the delete-and-recreate idiom must make a reload a no-op
    # in effect. -a shows handles; a rule line is two tabs deep with a
    # handle, which chain headers and "type ... hook" lines are not.
    my $out = qx(unshare -rn sh -c 'nft -c -f "$file" && nft -f "$file" && nft -f "$file" && nft -a list ruleset' 2>&1);
    is($? >> 8, 0, 'nft checks and loads the ruleset, twice (idempotent)') or diag($out);
    is(scalar(grep { /^\t\t.*# handle \d+$/ } split /\n/, $out), scalar(@{ $ipt->{rules} }), 'the loaded ruleset has one nft rule per iptables rule');
    is(scalar(() = $out =~ /^table ip /mg), 4, 'exactly genfw\'s four tables exist');
    like($out, qr/^\t\ttype filter hook input priority filter; policy drop;$/m, 'INPUT is a base chain with DROP policy');
    like($out, qr/^\t\ttype nat hook postrouting priority srcnat; policy accept;$/m, 'POSTROUTING is a nat base chain');
    like($out, qr/^\t\toifname "eth0" ip saddr 192\.168\.1\.0\/24 counter packets 0 bytes 0 masquerade # handle/m, 'the MASQUERADE rule is present as nft sees it');
}

done_testing;
